spring.application.name=TheBeliever
spring.datasource.url=jdbc:postgresql://ep-twilight-paper-abrl8jiz-pooler.eu-west-2.aws.neon.tech/TheBelieverDatabase?user=TheBelieverDatabase_owner&password=npg_2Bl4WtmPrGqz&sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
