spring.application.name=TheBeliever
spring.datasource.url=jdbc:postgresql://ep-twilight-paper-abrl8jiz-pooler.eu-west-2.aws.neon.tech/TheBelieverDatabase?user=TheBelieverDatabase_owner&password=npg_2Bl4WtmPrGqz&sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#Email Properties
spring.mail.host=smtp.mailgun.org
spring.mail.port=587
spring.mail.username=${SMTP_USERNAME}
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


